CREATE TABLE links (
    id INT AUTO_INCREMENT PRIMARY KEY,
    original_link VARCHAR(100) NOT NULL UNIQUE,
    short_link VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
